### PR TITLE
Blur2

### PR DESCRIPTION
**Pull request by ATechnoHazard**

### CODE REVIEW

**Comment by rm-rfasterisk** [comment]
VERY NICE JOB @ATechnoHazard PolyOS P with VoLTE and kernel with many governors when?

**Comment by ATechnoHazard** [comment]
Shhhh it's a part of my embarrassing history ;__;

**Comment by mvaisakh** [comment]
Because why not xD

**Comment by p8tgames** [comment]
I'm late to the party I think

**Comment by ATechnoHazard** [comment]
;________;

**Comment by p8tgames** [comment]
wen polyos Oreo sar

**Pull request merged**
